import { randomUUID } from "node:crypto";
import type { IncidentContextV1 } from "./incident-context";
import type { Hypothesis } from "./hypothesis-engine";
import type { AppConfig } from "../config/env";
import { requestGithubRuntimeAccess } from "../identity/teleport-github";

export interface RemediationProposal {
  branchName: string;
  commitMessage: string;
  prTitle: string;
  prBody: string;
  patchSummary: string;
}

export async function createRemediationProposal(
  config: AppConfig,
  context: IncidentContextV1,
  hypotheses: Hypothesis[],
): Promise<RemediationProposal> {
  await requestGithubRuntimeAccess(config, {
    scope: "pr:create",
    reason: `remediation:${context.incidentId}`,
  });

  const top = hypotheses[0];
  const slug = context.incidentId.toLowerCase().replace(/[^a-z0-9-]/g, "-");
  const branchName = `agent/remediate/${slug}-${randomUUID().slice(0, 8)}`;

  const patchSummary = top
    ? `Apply guarded fallback + timeout handling for suspected cause: ${top.id}`
    : "Apply observability-focused defensive patch";

  const prTitle = `[Agent] Remediation proposal for incident ${context.incidentId}`;
  const commitMessage = `fix(agent): propose remediation for ${context.incidentId}`;

  const prBody = [
    `## Incident`,
    `- ID: ${context.incidentId}`,
    `- Service: ${context.service}`,
    context.correlationId ? `- Correlation: ${context.correlationId}` : undefined,
    ``,
    `## Top hypothesis`,
    top
      ? `- ${top.id} (confidence: ${top.confidence})\n- ${top.summary}`
      : `- none (insufficient evidence)`,
    ``,
    `## Proposed patch`,
    `- ${patchSummary}`,
    ``,
    `## Evidence`,
    `- logs: ${context.evidence.logs ? "present" : "missing"}`,
    `- metrics: ${context.evidence.metrics ? "present" : "missing"}`,
    `- deploy metadata: ${context.evidence.deploy ? "present" : "missing"}`,
    ``,
    `> Generated by oncall-agent runtime workflow.`,
  ]
    .filter(Boolean)
    .join("\n");

  return { branchName, commitMessage, prTitle, prBody, patchSummary };
}
