/**
 * Core domain types for the on-call agent.
 * Defines incident shape, agent state, tool contracts, audit events.
 * No implementation — types only.
 */

import type { AuditEvent } from "../audit/audit-model";

// Re-export audit types for convenience
export type { AuditEvent };

/**
 * Incident received from upstream system.
 * Example: alerting platform, incident management system, etc.
 */
export interface Incident {
  incident_id: string;           // unique identifier
  title: string;                 // short description
  severity: "SEV1" | "SEV2" | "SEV3" | "SEV4";  // priority level
  service: string;               // affected service
  started_at: string;            // ISO 8601 timestamp
  summary: string;               // detailed context (POTENTIALLY UNTRUSTED)
  initial_context?: string;      // additional metadata
}

/**
 * A message exchanged with the LLM model.
 */
export interface ModelMessage {
  role: "user" | "assistant";
  content: string;
  timestamp: string;             // ISO 8601
}

/**
 * A tool call generated by the model.
 * Parsed from model output (e.g., Claude's tool_use block).
 */
export interface ToolCall {
  id: string;                    // unique call ID (for tracking)
  name: string;                  // tool name (e.g., "query_logs")
  arguments: Record<string, unknown>;  // input arguments
  requestedAt: string;           // ISO 8601 timestamp when model generated

  // Filled in after execution/blocking
  executedAt?: string;           // when tool actually ran (or was blocked)
  blocked?: boolean;             // true if blocked by safety check
  blockedReason?: string;        // why it was blocked ("dangerous pattern", etc.)
}

/**
 * Result from executing a tool.
 */
export interface ToolResult {
  toolName: string;
  callId: string;
  success: boolean;
  output?: unknown;              // the tool's return value
  error?: {
    code: string;
    message: string;
  };
}

/**
 * Full agent execution state, returned at end of investigation.
 */
export interface AgentState {
  incidentId: string;

  // Execution tracking
  status: "running" | "completed" | "failed" | "blocked";
  attempt: number;               // which attempt (usually 1)

  // Messages exchanged with model
  messagesExchanged: ModelMessage[];

  // Tool calls (parsed from model output)
  toolCalls: ToolCall[];

  // Audit trail (detailed event log)
  auditTrail: AuditEvent[];

  // Final output
  finalSummary: string | null;   // the incident summary to post

  // Summary stats
  toolCallsRequested: number;
  toolCallsExecuted: number;
  toolCallsBlocked: number;
  blockedReasons: Record<string, number>;  // { reason: count }
  unsafePatternsDetected: number;

  // Timing
  startedAt: string;             // ISO 8601
  completedAt: string;           // ISO 8601
}

/**
 * Import this in audit-model.ts and other modules.
 */
export {};